kind: pipeline
name: drone-CICD
image: docker
steps:
- name: unit-test
  image: node:latest
  environment:
    MYSQL_USER: hsipl
    MYSQL_PASSWORD: hsipl211
    MYSQL_ROOT_PASSWORD: hsipl211
    MYSQL_DATABASE: dev_db
  commands:
    - bash ./build.sh

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/prd/order_system
      - git pull 

trigger:
  branch: 
    - main
    - Backend/add-store-test
  event: 
    - pull_request
