kind: pipeline
name: drone-CICD for prd

steps:
- name: unit-test
  image: python
  commands:
  - echo "ok!" 

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/prd/order_system
      - git pull 
      # - chmod 777 scripts/run_docker.sh
      # - cd scripts/ && ./run_docker.sh

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: order_system
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - main
  event: 
    - pull_request

---
kind: pipeline
name: drone-CICD for dev

steps:
- name: unit-test
  image: python
  commands:
  - echo "ok!" 

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/dev/order_system
      - git pull
      - chmod 777 scripts/run_docker.sh
      - cd scripts/ && ./run_docker.sh 

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: order_system
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - dev
  event: 
    - push

