services:
- name: db
  image: mysql
  environment:
    MYSQL_USER: hsipl
    MYSQL_PASSWORD: hsipl211
    MYSQL_ROOT_PASSWORD: hsipl211
    MYSQL_DATABASE: dev_db
- name: redis
  image: redis:alpine

kind: pipeline
name: Build for production
type: docker

trigger:
  branch: 
    - main
  event: 
    - pull_request



  
steps:
- name: Run Test
  image: node:latest
  depends_on:
    - db
    - redis
  commands:
    - sleep 10
    - echo "start running test..."
    - bash ./build.sh
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/prd/order_system
      - git pull 
    when:
      branch:
        - main
      event:
        - push
---

kind: pipeline
type: docker
name: drone-CICD for dev

steps:
- name: Run Test
  image: node:latest
  depends_on:
    - db
    - redis
  commands:
    - sleep 5
    - echo "start running test..."
    - bash ./build.sh
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/dev/order_system
      - git pull 
    when:
      branch:
        - development
      event:
        - push