kind: pipeline
name: drone-CICD

steps:
- name: Build Docker Environment
  image: docker/compose:1.25.0-rc2-alpine
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - cd ./server
    - docker-compose up -d db redis

- name: unit-test
  image: node:latest
  commands:
    - bash ./build.sh

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: host 
    username: 
      from_secret: user 
    password: 
      from_secret: password 
    port: 22
    script:
      - cd /home/hsipl/feng/Order_System/prd/order_system
      - git pull 

trigger:
  branch: 
    - main
    - Backend/add-store-test
  event: 
    - pull_request

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock