kind: pipeline
name: Build for production
type: docker

services:
- name: db
  image: mysql
  environment:
    MYSQL_USER: hsipl
    MYSQL_PASSWORD: hsipl211
    MYSQL_ROOT_PASSWORD: hsipl211
    MYSQL_DATABASE: dev_db

- name: redis
  image: redis:alpine

steps:
- name: Run Test
  image: node:latest
  depends_on:
    - db
    - redis
  commands:
    - echo "start running test..."
    - bash ./build.sh

- name: slack
  image: plugins/slack
  depends_on:
      - Run Test
  settings:
    webhook:
      from_secret: slack_webhook
    channel: order_system
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - main
  event: 
    - pull_request
---

kind: pipeline
type: docker
name: drone-CICD for dev

services:
- name: db
  image: mysql
  environment:
    MYSQL_USER: hsipl
    MYSQL_PASSWORD: hsipl211
    MYSQL_ROOT_PASSWORD: hsipl211
    MYSQL_DATABASE: dev_db
    
- name: redis
  image: redis:alpine

steps:
- name: Run Test
  image: node:latest
  depends_on:
    - db
    - redis
  commands:
    - echo "start running test..."
    - bash ./build.sh

- name: slack
  image: plugins/slack
  depends_on:
      - Run Test
  settings:
    webhook:
      from_secret: slack_webhook
    channel: order_system
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - development
  event: 
    - push    
