version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: hsipl
      MYSQL_PASSWORD: hsipl211
      MYSQL_ROOT_PASSWORD: hsipl211
      MYSQL_DATABASE: dev_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - order_net

  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - order_net

  backend:
    build: .
    restart: always
    environment:
      MODE: dev
      PORT: 8000
      DEV_USERNAME: hsipl
      DEV_PASSWORD: hsipl211
      DEV_HOST: db
      DEV_PORT: 3306
      DEV_DB: dev_db
    links:
      - db
    ports:
      - 8000:8000
    networks:
      - order_net
    depends_on:
      - db
    command: sh -c "yarn migrate && yarn dev"
    
    volumes:
      - backend_data:/order_system/server

volumes:
  mysql_data:
  backend_data:
  redis_data:

networks:
  order_net:
    driver: bridge
