services:
  admin:
    build: .
    restart: always
    ports:
      - 3003:3003
    networks:
      - order_net
    volumes:
      - admin_data:/order_system/server
    command: yarn start

networks:
  order_net:
    driver: bridge

volumes:
  admin_data:
